---
title: "Research on COVID-19 vaccination"
author:
- familyname: Anukarnsakulchularp
  othernames: Krisanat
  address: Monash University
  email: kanu0003@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
- familyname: Vatsal
  othernames: Kumar
  address: Monash University
  email: kvat0001@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
- familyname: Zhou
  othernames: Xiyun 
  address: Monash University
  email: xzho0054@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Actuarial Studies
- familyname: Hu
  othernames: Xinyu
  address: Monash University
  email: xhu103@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Applied Economics and Econometrics  
department: Subject ETC5513\newline Group Name\newline Quad Squad
organization: Monash University
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(rmarkdown) 
library(bookdown) 
library(readr) 
library(bookdown) 
library(kableExtra) 
library(dplyr) 
library(knitr) 
library(ggplot2) 
library(plotly) 

```


\clearpage
# **Introduction** 

Since the first outbreak of Covid-19 in late 2019, there have been more than 500 million confirmed cases. To curb the spread, governments around the world had taken several measures like imposing restrictions on travelling, lockdown, and introducing social-distance. 

To bring this pandemic to an end, a large share of the world needs to be immune to the virus. The safest way to achieve this is with a vaccine. Vaccines are a technology that humanity has often relied on in the past to bring down the death toll of infectious diseases.

Fortunately in 2021, COVID-19 vaccines were introduced, it would require an incredibly-high vaccination rate to reduce the spread of the virus. Although the vaccines are not able to prevent infection, yet they are efficient at keeping the mortality rate low. “You may wonder if the vaccine is so effective, why are we still having a growth in the infection rate.”

We collected data from a public data base in github [COVID-19 data](https://github.com/owid/covid-19-data/tree/master/public/data). In this report, we would like to focus on overall COVID-19 analysis and relationship between the pandemic and the vaccination by the world range. 

The packages we will be using in this analysis are @tidyverse, @readr, @kableExtra, @bookdown, @bookdown2, and @ggplot2



\clearpage


# **Research questions** :

##The overall analysis of covid-19.

##The Effects of government policies on the spread of COVID- 19 worldwide. 

##How do positive cases change relate to vaccination? 

##How do death rates from COVID-19 differ between people who are vaccinated and those who are not?  



\clearpage


# **Exploratory data analysis** 




\clearpage


\section*{}

Question 1



\clearpage





**Research Question 2**







\clearpage


\section*{}




\section*{}



**CONCLUSIONS**

